routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionsController')->except('show');

//Route::post('/questions/{question}/answers', 'AnswersController@store')->name('answers.store');
Route::resource('questions.answers', 'AnswersController')->except(['index', 'create', 'show']);

Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');
//Route::post('/answers/{answer}/accept', 'AcceptAnswerController@store@store')->name('answers.accept');
Route::post('/questions/{question}/favourites', 'FavouritesController@store')->name('questions.favourite');
Route::delete('/questions/{question}/favourites', 'FavouritesController@destroy')->name('questions.unfavourite');
Route::post('/questions/{question}/vote', 'VoteQuestionController');
Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Answer.php
<?php
    
    namespace App;
    
    use function foo\func;
    use Illuminate\Database\Eloquent\Model;
   // use PhpParser\Node\Stmt\Static_;

    class Answer extends Model
    {
        
        use VotableTrait;
        
        protected $fillable = ['body', 'user_id'];
        
        public function question()
        {
            return $this->belongsTo(Question::class);
        }
        
        public function user(){
            return $this->belongsTo(User::class);
        }
    
        public function getBodyHtmlAttribute()
        {
            return clean(\Parsedown::instance()->text($this->body));
        }
        
        public static function boot(){
            parent::boot();
            
            static::created(function ($answer){
           $answer->question->increment('answers_count');
           
            });
            
            static::deleted(function ($answer){
                $answer->question->decrement('answers_count');
            });
        }
    
        public function getCreatedDateAttribute()
        {
            return $this->created_at->diffForHumans();
        }
    
        public function getStatusAttribute()
        {
            return $this->id == $this->question->best_answer_id ? 'vote-accepted' : '';
        }
    
       
    }

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question, Request $request)
    {
        
        $question->answers()->create($request->validate(['body' => 'required']) + ['user_id' => \Auth::id()]);
      
        return back()->with('success', "Your Answer has been submitted successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function show(Answer $answer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question , Answer $answer)
    {
        $this->authorize('update', $answer);
        
        return view('answers._edit', compact('question','answer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);
        
        $answer->update($request->validate
        (['body' => 'required',]));
        
        return redirect()->route('questions.show', $question->slug)->with('success', 'Your answer has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question, Answer $answer)
    {
    $this->authorize('delete', $answer);
    $answer->delete();
    
    return back()->with('success', "Your answer has been removed");
    }
}

resources/views/answers/_create.blade.php
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h2>Your Answer</h2>
                </div>
                <hr>
                <form action="{{ route('questions.answers.store', $question->id) }}" method="post">
                    @csrf
                    <div class="form-group">
                        <textarea class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}" name="body" rows="7"></textarea>
                    </div>
                        @if($errors->has('body'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('body') }}</strong>
                            </div>
                        @endif

                    <div class="form-group">
                        <button type="submit" class="btn btn-lg btn-outline-primary">Submit</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row mt-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <h1>Editing answer for question: <strong>{{ $question->title }}</strong></h1>
                        </div>
                        <hr>
                        <form action="{{ route('questions.answers.update', [$question->id, $answer->id] ) }}"
                              method="post">
                            @csrf
                            @method('PATCH')
                            <div class="form-group">
                                <textarea class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}"
                                          name="body" rows="7">{{ old('body', $answer->body) }}</textarea>
                            </div>
                            @if($errors->has('body'))
                                <div class="invalid-feedback">
                                    <strong>{{ $errors->first('body') }}</strong>
                                </div>
                            @endif

                            <div class="form-group">
                                <button type="submit" class="btn btn-lg btn-outline-primary">Update</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    $@endsection

resources/views/answers/_index.blade.php
@if($answersCount > 0)
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h2>{{ $answersCount ." ". Str::plural('Answer', $answersCount)}}</h2>
                    </div>
                    <hr>
                    @include('layouts._messages')
                    @foreach($answers as $answer)
                        <div class="media">
                            <div class="d-flex flex-column vote-controls">
                                <a title="This answer is useful" class="vote-up {{ Auth::guest() ? 'off' : '' }}"
                                   onclick="event.preventDefault(); document.getElementById('up-vote-question-{{ $answer->id }}').submit();">
                                    <i class="fa fa-caret-up fa-3x"></i>
                                </a>
                                <form action="/answers/{{ $answer->id }}/vote" method="post"
                                      id="up-vote-question-{{ $answer->id }}" style="display: none;">
                                    @csrf
                                    <input type="hidden" name="vote" value="1">
                                </form>
                                <span class="votes-count">{{ $answer->votes_count }}</span>
                                <a title="This answer is not useful"
                                   class="vote-down {{ Auth::guest() ? 'off' : '' }}"
                                   onclick="event.preventDefault(); document.getElementById('down-vote-question-{{ $answer->id }}').submit();">
                                    <i class="fa fa-caret-down fa-3x"></i>
                                </a>
                                <form action="/answers/{{ $answer->id }}/vote" method="post"
                                      id="down-vote-question-{{ $answer->id }}" style="display: none;">--}}
                                    @csrf
                                    <input type="hidden" name="vote" value="-1">
                                </form>
                                {{--                            <a title="Mark this answer as best answer" class="{{ $answer->status }} mt-2"--}}
                                {{--                            onclick="event.preventDefault(); document.getElementById('accept-answer-{{ $answer->id }}').submit();"--}}
                                {{--                            >--}}
                                <i class="fa fa-check fa-2x"></i>
                                </a>
                                {{--                            <form action="{{ route('answer.accept', $answer->id) }}" method="post" id="accept-answer-{{ $answer->id }}" style="display: none;">--}}
                                {{--@csrf--}}
                                {{--                            </form>--}}
                            </div>
                            <div class="media-body">
                                {!! $answer->body_html !!}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="ml-auto">
                                            @can('update', $answer)
                                                <a href="{{ route('questions.answers.edit',[$question->id,$answer->id]) }}"
                                                   class="btn btn-sm btn-outline-info">Edit</a>
                                            @endcan
                                            @can('delete', $answer)
                                                <form method="post" class="form-delete"
                                                      action="{{ route('questions.answers.destroy', [$question->id, $answer->id]) }}">
                                                    @method('DELETE')
                                                    {{ csrf_field() }}
                                                    <button type="submit" class="btn btn-sm btn-outline-danger"
                                                            onclick="return confirm('Are you sure')">Delete
                                                    </button>
                                                </form>
                                            @endcan
                                        </div>
                                    </div>
                                    <div class="col-4"></div>
                                    <div class="col-4">
                                        @include('shared._author', [
                                        'model' => $answer,
                                        'label' => 'answered'
                                        ])
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endif