routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionsController')->except('show');

//Route::post('/questions/{question}/answers', 'AnswersController@store')->name('answers.store');
Route::resource('questions.answers', 'AnswersController')->except(['index', 'create', 'show']);

Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');
//Route::post('/answers/{answer}/accept', 'AcceptAnswerController@store@store')->name('answers.accept');
Route::post('/questions/{question}/favourites', 'FavouritesController@store')->name('questions.favourite');
Route::delete('/questions/{question}/favourites', 'FavouritesController@destroy')->name('questions.unfavourite');
Route::post('/questions/{question}/vote', 'VoteQuestionController');
Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Question.php
<?php
    
    namespace App;
    
    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Support\Str;
    
    class Question extends Model
    {
        use VotableTrait;
        
        protected $fillable = ['title', 'body'];
        
        public function user()
        {
            return $this->belongsTo(User::class);
        }
        
        public function setTitleAttribute($value)
        {
            $this->attributes['title'] = $value;
            $this->attributes['slug'] = Str::slug($value);
        }
        
//        public function setBodyAttribute($value)
//        {
//            $this->attributes['body'] = clean($value);
//        }
        
        public function getUrlAttribute()
        {
            return route("questions.show", $this->slug);
        }
        
        public function getCreatedDateAttribute()
        {
            return $this->created_at->diffForHumans();
        }
        
        public function getStatusAttribute()
        {
            if ($this->answers_count > 0):
                if ($this->best_answer_id):
                    return "answered accepted";
                endif;
                return "answered";
            endif;
            return "unanswered";
        }
        
        public function getBodyHtmlAttribute()
        {
        return clean($this->bodyHtml());
        }
        
        public function answers()
        {
            return $this->hasMany(Answer::class)->orderBy('votes_count', 'DESC');
        }
        
        public function acceptBestAnswer(Answer $answer)
        {
            $this->best_answer_id = $answer->id;
            $this->save();
        }
        
        public function favourites()
        {
            return $this->belongsToMany(User::class, 'favourites')->withTimestamps(); //, 'question_id', 'user_id')
        }
        
        public function isFavourited()
        {
            
            return $this->favourites()->where('user_id', auth()->id())->count() > 0;
        }
        
        public function getIsFavouritedAttribute()
        {
            return $this->isFavourited();
        }
        
        /**
         * @return mixed
         */
        public function getFavouritesCountAttribute()
        {
            return $this->favourites()->count();
        }
        
        public function getExcerptAttribute()
        {
            return $this->excerpt(250);
        }
        
        public function excerpt($length)
        {
            return Str::limit(strip_tags($this->bodyHtml()), $length);
        }
        
        private function bodyHtml()
        {
            return \Parsedown::instance()->text($this->body);
        }
    }

app/Http/Controllers/QuestionsController.php
<?php
    
    namespace App\Http\Controllers;
    
    use App\Http\Requests\AskQuestionRequest;
    use App\Question;
    use http\Exception;
    use Illuminate\Http\Request;
    
    class QuestionsController extends Controller
    {
        public function __construct()
        {
            $this->middleware('auth', ['except' => ['index', 'show']]);
        }
        
        /**
         * Display a listing of the resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function index()
        {
            \DB::enableQueryLog();
            $questions = Question::with('user')->latest()->paginate(5);
            
            return view('questions.index', compact('questions'));
            
        }
        
        /**
         * Show the form for creating a new resource.
         *
         * @return \Illuminate\Http\Response
         */
        public function create()
        {
            $question = new Question();
            
            return view('questions.create', compact('question'));
        }
        
        /**
         * Store a newly created resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @return \Illuminate\Http\Response
         */
        public function store(AskQuestionRequest $request)
        {
            
            $request->user()->questions()->create($request->only('title', 'body'));
            return redirect()->route('questions.index')->with('success',
                'Your Question has been submitted successfully');
        }
        
        /**
         * Display the specified resource.
         *
         * @param  \App\Question  $question
         * @return \Illuminate\Http\Response
         */
        public function show(Question $question)
        {
            //dd($question);
            $question->increment('views');
            
            return view('questions.show', compact('question'));
        }
        
        /**
         * Show the form for editing the specified resource.
         *
         * @param  \App\Question  $question
         * @return \Illuminate\Http\Response
         */
        public function edit(Question $question)
        {
            $this->authorize('update', $question);
            if (\Gate::denies('update-question', $question)) {
                abort(403, "Access denied");
            }
            return view('questions.edit', compact('question'));
        }
        
        /**
         * Update the specified resource in storage.
         *
         * @param  \Illuminate\Http\Request  $request
         * @param  \App\Question  $question
         * @return \Illuminate\Http\Response
         */
        public function update(AskQuestionRequest $request, Question $question)
        {
            $this->authorize('update', $question);
            if (\Gate::denies('update-question', $question)) {
                abort(403, "Access denied");
            }
            $question->update($request->only('title', 'body'));
            
            return redirect('/questions')->with('success', 'Your question has been updated.');
        }
        
        /**
         * Remove the specified resource from storage.
         *
         * @param  \App\Question  $question
         * @return \Illuminate\Http\Response
         */
        public function destroy(Question $question)
        {
            $this->authorize('delete', $question);
            if (\Gate::denies('delete-question', $question)) {
                abort(403, "Access denied");
            }
            $question->delete();
            return redirect('/questions')->with('success', 'Your question has been deleted.');
        }
    }

resources/views/questions/_form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <lable for="question-title">Question Title</lable>
    <input type="text" name="title" value="{{ old('title', $question->title) }}" id="question-title" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">
    @if($errors->has('title'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('title') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <lable for="question-body">Explain you question</lable>
    <textarea name="body" id="question-body" rows="10" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}">{{ old('body', $question->body) }}</textarea>
    @if($errors->has('body'))
        <div class="invalid-feedback">
            <strong>{{ $errors->first('body') }}</strong>
        </div>
    @endif
</div>
<div class="form-group">
    <button type="submit" class="btn-outline-primary btn-lg">{{ $buttonText }}</button>
</div>

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                        <h2>Ask Questions</h2>
                            <div class="ml-auto">
                                <a href="{{ route('questions.index') }}" class="btn btn-outline-secondary">Back to all Question</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method = "post">
                            @include('questions._form', ['buttonText' => "Ask Question"])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>Edit Questions</h2>
                            <div class="ml-auto">
                                <a href="{{ route('questions.index') }}" class="btn btn-outline-secondary">Back to all Question</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('questions.update', $question->id) }}" method = "post">
                            {{ method_field('PUT') }}
                            @include('questions._form', ['buttonText' => "Ask Question"])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h2>All Questions</h2>
                            <div class="ml-auto">
                                <a href="{{route('questions.create')}}" class="btn btn-outline-secondary">Ask
                                    Question</a>
                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        @include('layouts._messages')
                        @forelse($questions as $question)
                            <div class="media">
                                <div class="d-flex flex-column counters">
                                    <div class="vote">
                                        <strong>{{ $question->votes_count }}</strong>{{ Str::plural('vote', $question->votes_count) }}
                                    </div>
                                    <div class="status {{ $question->status }} answer">
                                        <strong>{{ $question->answers_count }}</strong>{{ Str::plural('answer', $question->answers_count) }}
                                    </div>
                                    <div class="view">
                                        {{ $question->views .' '. Str::plural('view', $question->views) }}
                                    </div>
                                </div>
                                <div class="media-body">
                                    <div class="d-flex align-items-center">
                                        <h3 class="mt-0"><a href="{{ $question->url }}">{{ $question->title }}</a></h3>
                                        <div class="ml-auto">
                                            @can('update', $question)
                                                <a href="{{ route('questions.edit',$question->id) }}"
                                                   class="btn btn-sm btn-outline-info">Edit</a>
                                            @endcan
                                            @can('delete', $question)
                                                <form method="post" class="form-delete"
                                                      action="{{ route('questions.destroy', $question->id) }}">
                                                    @method('DELETE')
                                                    {{ csrf_field() }}
                                                    <button type="submit" class="btn btn-sm btn-outline-danger"
                                                            onclick="return confirm('Are you sure')">Delete
                                                    </button>
                                                </form>
                                            @endcan
                                        </div>
                                    </div>
                                    <p class="lead">
                                        Asked by
                                        <a href="{{ $question->user->url }}">{{ $question->user->name }}</a>
                                        <small class="text-muted">{{ $question->created_date }}</small>
                                    </p>
                                    <div class="excerpt">{{ $question->excerpt(350) }}</div>

                                </div>
                            </div>
                            <hr/>
                            @empty
                            <div class="alert alert-warning">
                                <strong>Sorry</strong>There are no questions available.
                            </div>
                        @endforelse
                        <div class="justify-content-center">
                            {{ $questions->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-title">
                            <div class="d-flex align-items-center">
                                <h1>{{ $question->title }}</h1>
                                <div class="ml-auto">
                                    <a href="{{ route('questions.index') }}" class="btn btn-outline-secondary">Back to
                                        all
                                        Question</a>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="media">
                            @include ('shared._vote', [
                            'model' => $question
                            ])
                            <div class="media-body">
                                {!! $question->body_html !!}
                                <div class="row">
                                    <div class="col-4"></div>
                                    <div class="col-4"></div>
                                    <div class="col-4">
                                        @include('shared._author', [
                                        'model' => $question,
                                        'label' => 'asked'
                                        ])
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @include('answers._index',[
        'answersCount' => $question->answers_count,
        'answers' => $question->answers,
        ])
        @include('answers._create')
    </div>
@endsection