routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionsController')->except('show');

//Route::post('/questions/{question}/answers', 'AnswersController@store')->name('answers.store');
Route::resource('questions.answers', 'AnswersController')->except(['index', 'create', 'show']);

Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');
//Route::post('/answers/{answer}/accept', 'AcceptAnswerController@store@store')->name('answers.accept');
Route::post('/questions/{question}/favourites', 'FavouritesController@store')->name('questions.favourite');
Route::delete('/questions/{question}/favourites', 'FavouritesController@destroy')->name('questions.unfavourite');
Route::post('/questions/{question}/vote', 'VoteQuestionController');
Route::post('/answers/{answer}/vote', 'VoteAnswerController');

app/Answer.php
<?php
    
    namespace App;
    
    use function foo\func;
    use Illuminate\Database\Eloquent\Model;
   // use PhpParser\Node\Stmt\Static_;

    class Answer extends Model
    {
        
        use VotableTrait;
        
        protected $fillable = ['body', 'user_id'];
        
        public function question()
        {
            return $this->belongsTo(Question::class);
        }
        
        public function user(){
            return $this->belongsTo(User::class);
        }
    
        public function getBodyHtmlAttribute()
        {
            return clean(\Parsedown::instance()->text($this->body));
        }
        
        public static function boot(){
            parent::boot();
            
            static::created(function ($answer){
           $answer->question->increment('answers_count');
           
            });
            
            static::deleted(function ($answer){
                $answer->question->decrement('answers_count');
            });
        }
    
        public function getCreatedDateAttribute()
        {
            return $this->created_at->diffForHumans();
        }
    
        public function getStatusAttribute()
        {
            return $this->id == $this->question->best_answer_id ? 'vote-accepted' : '';
        }
    
       
    }

app/Question.php
<?php
    
    namespace App;
    
    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Support\Str;
    
    class Question extends Model
    {
        use VotableTrait;
        
        protected $fillable = ['title', 'body'];
        
        public function user()
        {
            return $this->belongsTo(User::class);
        }
        
        public function setTitleAttribute($value)
        {
            $this->attributes['title'] = $value;
            $this->attributes['slug'] = Str::slug($value);
        }
        
//        public function setBodyAttribute($value)
//        {
//            $this->attributes['body'] = clean($value);
//        }
        
        public function getUrlAttribute()
        {
            return route("questions.show", $this->slug);
        }
        
        public function getCreatedDateAttribute()
        {
            return $this->created_at->diffForHumans();
        }
        
        public function getStatusAttribute()
        {
            if ($this->answers_count > 0):
                if ($this->best_answer_id):
                    return "answered accepted";
                endif;
                return "answered";
            endif;
            return "unanswered";
        }
        
        public function getBodyHtmlAttribute()
        {
        return clean($this->bodyHtml());
        }
        
        public function answers()
        {
            return $this->hasMany(Answer::class)->orderBy('votes_count', 'DESC');
        }
        
        public function acceptBestAnswer(Answer $answer)
        {
            $this->best_answer_id = $answer->id;
            $this->save();
        }
        
        public function favourites()
        {
            return $this->belongsToMany(User::class, 'favourites')->withTimestamps(); //, 'question_id', 'user_id')
        }
        
        public function isFavourited()
        {
            
            return $this->favourites()->where('user_id', auth()->id())->count() > 0;
        }
        
        public function getIsFavouritedAttribute()
        {
            return $this->isFavourited();
        }
        
        /**
         * @return mixed
         */
        public function getFavouritesCountAttribute()
        {
            return $this->favourites()->count();
        }
        
        public function getExcerptAttribute()
        {
            return $this->excerpt(250);
        }
        
        public function excerpt($length)
        {
            return Str::limit(strip_tags($this->bodyHtml()), $length);
        }
        
        private function bodyHtml()
        {
            return \Parsedown::instance()->text($this->body);
        }
    }

app/User.php
<?php
    
    namespace App;
    
    use Illuminate\Notifications\Notifiable;
    use Illuminate\Contracts\Auth\MustVerifyEmail;
    use Illuminate\Foundation\Auth\User as Authenticatable;
    
    class User extends Authenticatable
    {
        use Notifiable;
        
        /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
        protected $fillable = [
            'name', 'email', 'password',
        ];
        
        /**
         * The attributes that should be hidden for arrays.
         *
         * @var array
         */
        protected $hidden = [
            'password', 'remember_token',
        ];
        
        /**
         * The attributes that should be cast to native types.
         *
         * @var array
         */
        protected $casts = [
            'email_verified_at' => 'datetime',
        ];
        
        public function questions()
        {
            return $this->hasMany(Question::class);
        }
        
        public function getUrlAttribute()
        {
            return "#";
        }
        
        public function answers()
        {
            return $this->hasMany(Answer::class);
        }
        
        public function getAvatarAttribute()
        {
            $email = $this->email;
            $size = 32;
            
            return "https://www.gravatar.com/avatar/".md5(strtolower(trim($email)))."?s=".$size;
        }
        
        public function favourites()
        {
            return $this->belongsToMany(Question::class,
                'favourites')->withTimestamps(); //, 'author_id', 'question_id');
        }
        
        public function voteQuestions()
        {
            return $this->morphedByMany(Question::class, 'votable');
        }
        
        public function voteAnswers()
        {
            return $this->morphedByMany(Answer::class, 'votable');
        }
        
        /**
         * @param  Question  $question
         * @param $vote
         */
        public function voteQuestion(Question $question, $vote)
        {
            $voteQuestions = $this->voteQuestions();
            
            $this->_vote($voteQuestions, $question, $vote);
        }
        
        public function voteAnswer(Answer $answer, $vote)
        {
            $voteAnswers = $this->voteAnswers();
            
            $this->_vote($voteAnswers, $answer, $vote);
           
        }
        
        private function _vote($relationship, $model, $vote)
        {
            if ($relationship->where('votable_id', $model->id)->exists()):
        
                $relationship->updateExistingPivot($model, ['vote' => $vote]);
    
            else:
        
                $relationship->attach($model, ['vote' => $vote]);
    
            endif;
    
            $model->load('votes');
            $downVotes = (int) $model->downVotes()->sum('vote');
            $upVotes = (int) $model->upVotes()->sum('vote');
    
            $model->votes_count = $upVotes + $downVotes;
            $model->save();
        }
    }

resources/views/shared/_author.blade.php
<span class="text-muted"> {{ $label . " " . $model->created_date }}</span>
<div class="media mt-2">
    <a href="{{ $model->user->url }}" class="pr-2">
        <img src="{{ $model->user->avatar }}" alt="">
    </a>
    <div class="media-body mt-1">
        <a href="{{ $model->user->url }}">{{ $model->user->name }}</a>
    </div>
</div>

resources/views/shared/_favourite.blade.php
<a title="Click to mark as favourite Question (Click again to undo)"
   class="favourite mt-2 {{ Auth::guest() ? 'off' : ($model->is_favourited ? 'favourite' : '') }}"
   onclick="event.preventDefault(); document.getElementById('favourite-question-{{ $model->id }}').submit();">

    <i class="fa fa-star fa-2x"></i>
    <span class="favourite-count">{{ $model->favourites_count }}</span>
</a>
<form action="/questions/{{ $model->id }}/favourites" method="post"
      id="favourite-question-{{ $model->id }}" style="display: none;">--}}
    @csrf
    @if($model->is_favourited)
        @method ('DELETE')
    @endif
</form>

resources/views/shared/_vote.blade.php
@if ($model instanceof App\Question)
    @php
        $name ='question';
        $firstURISegment = 'questions';
    @endphp
@elseif ($model instanceof App\Answer)
    @php
        $name = 'answer';
        $firstURISegment = 'answers';
    @endphp
@endif

@php

$formId = $name . "_" . $model->id;
$formAction = "/{ $firstURISegment }/{ $model->id }/vote";


@endphp

<div class="d-flex flex-column vote-controls">
    <a title="This {{ $name }} is useful" class="vote-up {{ Auth::guest() ? 'off' : '' }}"
       onclick="event.preventDefault(); document.getElementById('up-vote-{{ $formId }}').submit();">
        <i class="fa fa-caret-up fa-3x"></i>
    </a>
    <form action="{{ $formAction }}" method="post"
          id="up-vote-{{ $formId }}" style="display: none;">
        @csrf
        <input type="hidden" name="vote" value="1">
    </form>
    <span class="votes-count">{{ $model->votes_count }}</span>
    <a title="This {{ $name }} is not useful"
       class="vote-down {{ Auth::guest() ? 'off' : '' }}"
       onclick="event.preventDefault(); document.getElementById('down-vote-question-{{ $formId }}').submit();">
        <i class="fa fa-caret-down fa-3x"></i>
    </a>
    <form action="{{ $formAction }}" method="post"
          id="down-vote-question-{{ $formId }}" style="display: none;">--}}
        @csrf
        <input type="hidden" name="vote" value="-1">
    </form>

    @include('shared._favourite', [
    'model' => $model
    ])

</div>